<?php

return [
  's3_folder' => '/japanese/kakuro/',
  'puzzles_folder' => '/puzzles/',
  'solutions_folder' => '/solutions/',
  'puzzle_name' => 'Kakuro',
  'solution_name' => 'Solution',
  'ext' => '.png',
  'type' => 'image/png',
  'max_number' => 10000,
  'width' => 2422,
  'height' => 2757,
  'size' => 120000,
  'difficulties' => [
    'Grid7' => '7x7 Grid',
    'prod-grid1' => 'Prod Grid 1',
    'prod-grid2' => 'Prod Grid 2',
    'prod-grid3' => 'Prod Grid 3',
    'prod-grid4' => 'Prod Grid 4',
    'prod-grid5' => 'Prod Grid 5',
    'prod-grid6' => 'Prod Grid 6',
    'prod-grid7' => 'Prod Grid 7',
    'prod-grid8' => 'Prod Grid 8',
    'prod-grid9' => 'Prod Grid 9',
    'prod-grid10' => 'Prod Grid 10',
    'prod-grid11' => 'Prod Grid 11',
    'prod-grid12' => 'Prod Grid 12',
    'prod-grid13' => 'Prod Grid 13',
    'prod-grid14' => 'Prod Grid 14',
    'prod-grid15' => 'Prod Grid 15',
    'sum-grid1' => 'Sum Grid 1',
    'sum-grid2' => 'Sum Grid 2',
    'sum-grid3' => 'Sum Grid 3',
    'sum-grid4' => 'Sum Grid 4',
    'sum-grid5' => 'Sum Grid 5',
    'sum-grid6' => 'Sum Grid 6',
    'sum-grid7' => 'Sum Grid 7',
    'sum-grid8' => 'Sum Grid 8',
    'sum-grid9' => 'Sum Grid 9',
    'sum-grid10' => 'Sum Grid 10',
    'sum-grid11' => 'Sum Grid 11',
    'sum-grid12' => 'Sum Grid 12',
    'sum-grid13' => 'Sum Grid 13',
    'sum-grid14' => 'Sum Grid 14',
    'sum-grid15' => 'Sum Grid 15',
    'sum-grid16' => 'Sum Grid 16',
 
  ],
  'addGroups' => [
    10, 25, 50, 100, 150, 200
  ],
];
